image:
  file: .devcontainer/Dockerfile

tasks:
  - init: "./run.fsx restore && ./run.fsx build"

vscode:
  extensions:
    - editorconfig.editorconfig
    - eamodio.gitlens
    - ybaumes.highlight-trailing-white-spaces
    - gruntfuggly.todo-tree
    - muhammad-sammy.csharp
    - ionide.ionide-fsharp
